name: "Tests: shellcheck"

on: [pull_request, push]

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        shell:
          - bash
          - sh
          - dash
          - ksh
          - zsh
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get install shellcheck zsh
      - name: Run shellcheck on nvm.sh
        run: shellcheck -s ${{ matrix.shell }} nvm.sh
      - name: Run shellcheck on install.sh
        if: ${{ matrix.shell == 'bash' }}
        run: shellcheck -s ${{ matrix.shell }} install.sh
